### PR TITLE
fix(frontend): change username label on login page

### PR DESCRIPTION
**Pull request by jackei1989**
correction label on login page Username or Password to Username or Email https://github.com/MESH-Research/CCR/issues/4

### CODE REVIEW

**Comment by jackei1989** [comment]
Dear @wreality I've sent a PR for this.
this was my first PR :)
Sorry if there was a problem.

**Comment by wreality** [comment]
Change looks great, but can you rebase your pull request off of the development branch instead of master please.

**Comment by wreality** [comment]
@jackei1989 You've got the right idea, but you merged development instead of rebasing.  I'll try to explain the difference and walk you through how to get it straightened out.

(Also [here's some good reading how/why to rebase a pull request](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request))

I changed the base branch for the pull request back to development (you had that part right :-) )

But, if you look up at the top of your merge request here, under Commits it lists "4", but only one of those commits relates to your changes (the one you made). We want the pull request to be just your changes and only the commits related to making that change.

How to fix it (in THIS case... note this isn't always the right way to fix it... read the link above for more info): 

1. Make sure we're on the issue branch you created
 `git checkout issue4`
1.  We need to get the merge commit out of there.
`git reset --hard HEAD~`
1. We're now rewriting history.. so we'll have to force push (usually a bad idea, but this branch isn't shared with anyone.. so we're good)
`git push -f`
1. Now that we've removed the commit, its time to rebase from the development branch.
1. Add the upstream (this repo) as a remote (if you've already done this, you don't need to do it again.. just use the name you used (if you didn't use the name "upstream").
`git remote add upstream https://github.com/MESH-Research/CCR.git`
1. Fetch the remote:
`git fetch upstream`
1. Rebase your branch on the upstream development branch:
`git rebase upstream/development`
1. Force push your branch to update the pull request:
`git push -f`

**Comment by wreality** [comment]
Cherry-picked with attribution in e8742d7501e

@jackei1989 thanks for the fix!

**Pull request closed without merging**
